### ISSUE TITLE
Packets not marked as ready when reconnecting

### ISSUE THREAD

**Issue by gregadams4** [kyren/turbulence#7]
Hey there,

Wondering if you have any insight, trying to walk through it myself but so far can't figure out how things should be. Basically if I have a server running and connect from another, everything works well. Then if I close down the client and reconnect shortly after, I can see packets being exchanged, but for some reason they are never marked as ready in windows.rs RecvWindow.

When this happens they are always padded in the front with zeros. Would you expect reconnecting to have weird issues like this? Unreliable messages do make it through, but reliable messages do not

Added some debug logging for myself trying to figure it out, not sure if it will be helpful for you, but here are some logs of values in RecvWindow recv method while working vs while not working after reconnecting

Working on initial connection:

```
received packet: [3, 0, 12, 0, 0, 0, 1, 0, 0]
data len: 3 packet len 3
start_pos: 12
receiving in window with start pos 12: [1, 0, 0]
self.recv_pos: 12, ready: 0
recv_start_pos: 12, recv_end_pos: 1036, end_pos: 15
copy_start_pos: 12 end_pos 15
data_start: 0, buf_start: 0 buf_end: 3
current buffer size: 0
current buffer: []
new buffer size: 3
new buffer: [1, 0, 0]
self.recv_pos: 12, start_pos: 12
```

Not Working when reconnecting:

```
received packet: [3, 0, 12, 0, 0, 0, 1, 0, 2]
data len: 3 packet len 3
start_pos: 12
receiving in window with start pos 12: [1, 0, 2]
self.recv_pos: 0, ready: 0
recv_start_pos: 0, recv_end_pos: 1024, end_pos: 15
copy_start_pos: 12 end_pos 15
data_start: 0, buf_start: 12 buf_end: 15
current buffer size: 0
current buffer: []
new buffer size: 15
new buffer: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2]
self.recv_pos: 0, start_pos: 12
```

Looks like this is because of the ordering guarantees and some missed packets while disconnected

**Comment by gregadams4** [comment]
So ya, looks like those zeros are reserved for the packets sent the last time to allow for ordering guarantees. But in this case it will never empty out because it waits indefinitely for messages that the server thinks have already been acknowledged.

Curious if you think that would be something for this package to handle internally or if the caller should always be making sure to use a new connection. Kind of difficult to guarantee if it isn't disconnected for longer than a keepalive or something though

**Comment by kyren** [comment]
I think what you're saying is that you have a connection between two reliable endpoints, and then on one side you close one and create a new endpoint and connect it to the other endpoint which doesn't know anything has happened?

If that's the case, that's not supposed to work.  The reliable endpoints maintain a shared state between them, a new connection should create two new endpoints.  It probably just so happens to work with unreliable connections because the unreliable connections don't maintain any state.  It would be the same as if you had a TCP server and client, and instead of creating new TCP state for a new connection on the server, you just started delivered packets from an entirely different client.

You are allowed to disconnect and reconnect the underlying transport though, as long as you maintain that both endpoints are kept alive and only packets from the original two endpoints are delivered to each other.  That's all it's designed to do.

Maybe I'm misunderstanding what's going on, though?
